import {
  FactoryData,
  TimelineSegment,
  TrendDataPoint,
  MetricTrendPoint,
} from "@/types/mes";

// Shared 24-hour trend series for Cycle Time, Speed, and Uptime
const sampleHourlyTrend: TrendDataPoint[] = [
  { time: "06:00", cycleTime: 1.15, speed: 52000, uptime: 94.2 },
  { time: "08:00", cycleTime: 1.12, speed: 54500, uptime: 96.5 },
  { time: "10:00", cycleTime: 1.28, speed: 48200, uptime: 88.0 },
  { time: "12:00", cycleTime: 1.14, speed: 53800, uptime: 95.1 },
  { time: "14:00", cycleTime: 1.1, speed: 55400, uptime: 97.4 },
  { time: "16:00", cycleTime: 1.22, speed: 50100, uptime: 91.3 },
  { time: "18:00", cycleTime: 1.11, speed: 55000, uptime: 96.8 },
  { time: "20:00", cycleTime: 1.13, speed: 54200, uptime: 95.5 },
  { time: "22:00", cycleTime: 1.18, speed: 51900, uptime: 93.7 },
];

const sampleTimeline: TimelineSegment[] = [
  {
    id: "t1",
    startTime: "06:00",
    endTime: "09:30",
    status: "ON",
    durationMinutes: 210,
    reason: "Normal Production",
  },
  {
    id: "t2",
    startTime: "09:30",
    endTime: "10:15",
    status: "OFF",
    durationMinutes: 45,
    reason: "Capper Head Jam (Breakdown)",
  },
  {
    id: "t3",
    startTime: "10:15",
    endTime: "10:45",
    status: "IDLE",
    durationMinutes: 30,
    reason: "Syrup Tank Sanitization",
  },
  {
    id: "t4",
    startTime: "10:45",
    endTime: "14:00",
    status: "ON",
    durationMinutes: 195,
    reason: "Normal Production",
  },
  {
    id: "t5",
    startTime: "14:00",
    endTime: "14:35",
    status: "OFF",
    durationMinutes: 35,
    reason: "Changeover to Coke Zero",
  },
  {
    id: "t6",
    startTime: "14:35",
    endTime: "18:15",
    status: "ON",
    durationMinutes: 220,
    reason: "Normal Production",
  },
  {
    id: "t7",
    startTime: "18:15",
    endTime: "18:40",
    status: "OFF",
    durationMinutes: 25,
    reason: "Labeler Sensor Cleaning",
  },
  {
    id: "t8",
    startTime: "18:40",
    endTime: "22:00",
    status: "ON",
    durationMinutes: 200,
    reason: "Normal Production",
  },
];

const generateTabbedMetrics = (
  baseOe: number,
  baseMtbf: number,
  baseUptime: number,
) => ({
  oe: [
    { time: "Mon", value: baseOe - 2.5, target: 85 },
    { time: "Tue", value: baseOe - 1.0, target: 85 },
    { time: "Wed", value: baseOe + 1.2, target: 85 },
    { time: "Thu", value: baseOe + 0.4, target: 85 },
    { time: "Fri", value: baseOe + 2.1, target: 85 },
    { time: "Sat", value: baseOe - 0.8, target: 85 },
    { time: "Sun", value: baseOe + 1.5, target: 85 },
  ],
  mtbf: [
    { time: "Mon", value: baseMtbf - 15, target: 180 },
    { time: "Tue", value: baseMtbf - 8, target: 180 },
    { time: "Wed", value: baseMtbf + 12, target: 180 },
    { time: "Thu", value: baseMtbf + 5, target: 180 },
    { time: "Fri", value: baseMtbf + 22, target: 180 },
    { time: "Sat", value: baseMtbf - 2, target: 180 },
    { time: "Sun", value: baseMtbf + 18, target: 180 },
  ],
  uptime: [
    { time: "Mon", value: baseUptime - 1.8, target: 95 },
    { time: "Tue", value: baseUptime - 0.5, target: 95 },
    { time: "Wed", value: baseUptime + 1.0, target: 95 },
    { time: "Thu", value: baseUptime + 0.2, target: 95 },
    { time: "Fri", value: baseUptime + 1.8, target: 95 },
    { time: "Sat", value: baseUptime - 0.4, target: 95 },
    { time: "Sun", value: baseUptime + 1.1, target: 95 },
  ],
});

export const factoriesData: FactoryData[] = [
  {
    id: "atlanta",
    name: "Atlanta Bottling Complex",
    location: "Atlanta, GA, USA",
    kpi: {
      factoryName: "Atlanta Bottling Complex",
      actualSpeed: 54200,
      actualProduction: 418500,
      lastHourCycleTime: 1.12,
      activeLinesRatio: { active: 5, total: 6 },
      oee: 84.6,
      sle: 91.4,
      usle: 88.2,
      productionVolume: 1420000,
      productionQuality: 99.4,
    },
    lossTree: {
      onPercentage: 84.6,
      offPercentage: 15.4,
      qualityLossPercentage: 3.2,
      speedLossPercentage: 6.8,
      reasons: [
        { name: "Breakdown", percentage: 4.8, durationMinutes: 69 },
        { name: "Cleansing process", percentage: 3.5, durationMinutes: 50 },
        { name: "Change over time", percentage: 3.2, durationMinutes: 46 },
        { name: "Idle", percentage: 2.4, durationMinutes: 35 },
        { name: "Minor stops", percentage: 1.5, durationMinutes: 22 },
      ],
    },
    timeline: sampleTimeline,
    trendData: sampleHourlyTrend,
    lines: [
      {
        id: "line-1",
        factoryId: "atlanta",
        name: "Line 1 — 500ml PET",
        type: "PET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 500ml PET",
          actualSpeed: 58000,
          actualProduction: 82400,
          lastHourCycleTime: 1.08,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 88.2,
          sle: 93.5,
          usle: 90.1,
          productionVolume: 285000,
          productionQuality: 99.7,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(88.2, 195, 96.4),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-2",
        factoryId: "atlanta",
        name: "Line 2 — 330ml Sleek Can",
        type: "Canning",
        status: "running",
        kpi: {
          factoryName: "Line 2 — 330ml Sleek Can",
          actualSpeed: 72000,
          actualProduction: 104500,
          lastHourCycleTime: 0.94,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 86.5,
          sle: 92.0,
          usle: 89.4,
          productionVolume: 360000,
          productionQuality: 99.2,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(86.5, 180, 95.0),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-3",
        factoryId: "atlanta",
        name: "Line 3 — 2.0L Family PET",
        type: "PET Bottling",
        status: "downtime",
        kpi: {
          factoryName: "Line 3 — 2.0L Family PET",
          actualSpeed: 28000,
          actualProduction: 38200,
          lastHourCycleTime: 1.62,
          activeLinesRatio: { active: 0, total: 1 },
          oee: 72.1,
          sle: 81.3,
          usle: 76.8,
          productionVolume: 145000,
          productionQuality: 98.6,
        },
        timeline: [
          {
            id: "l3-1",
            startTime: "06:00",
            endTime: "11:00",
            status: "ON",
            durationMinutes: 300,
            reason: "Normal Production",
          },
          {
            id: "l3-2",
            startTime: "11:00",
            endTime: "14:30",
            status: "OFF",
            durationMinutes: 210,
            reason: "Blow Molder Seal Rupture",
          },
          {
            id: "l3-3",
            startTime: "14:30",
            endTime: "22:00",
            status: "IDLE",
            durationMinutes: 450,
            reason: "Maintenance Scheduled",
          },
        ],
        tabbedMetrics: generateTabbedMetrics(72.1, 110, 84.5),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-4",
        factoryId: "atlanta",
        name: "Line 4 — 355ml Heritage Glass",
        type: "Glass Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 4 — 355ml Heritage Glass",
          actualSpeed: 42000,
          actualProduction: 61800,
          lastHourCycleTime: 1.25,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 83.4,
          sle: 89.8,
          usle: 86.5,
          productionVolume: 215000,
          productionQuality: 99.5,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(83.4, 165, 93.8),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "berlin",
    name: "Berlin Packaging Hub",
    location: "Berlin, Germany",
    kpi: {
      factoryName: "Berlin Packaging Hub",
      actualSpeed: 61500,
      actualProduction: 495000,
      lastHourCycleTime: 1.05,
      activeLinesRatio: { active: 4, total: 4 },
      oee: 89.1,
      sle: 94.6,
      usle: 92.3,
      productionVolume: 1680000,
      productionQuality: 99.8,
    },
    lossTree: {
      onPercentage: 89.1,
      offPercentage: 10.9,
      qualityLossPercentage: 1.8,
      speedLossPercentage: 4.2,
      reasons: [
        { name: "Breakdown", percentage: 3.1, durationMinutes: 45 },
        { name: "Cleansing process", percentage: 2.8, durationMinutes: 40 },
        { name: "Change over time", percentage: 2.4, durationMinutes: 35 },
        { name: "Idle", percentage: 1.6, durationMinutes: 23 },
        { name: "Minor stops", percentage: 1.0, durationMinutes: 14 },
      ],
    },
    timeline: [
      {
        id: "b1",
        startTime: "06:00",
        endTime: "12:00",
        status: "ON",
        durationMinutes: 360,
        reason: "Normal Production",
      },
      {
        id: "b2",
        startTime: "12:00",
        endTime: "12:40",
        status: "OFF",
        durationMinutes: 40,
        reason: "Cleansing cycle",
      },
      {
        id: "b3",
        startTime: "12:40",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 560,
        reason: "Normal Production",
      },
    ],
    trendData: [
      { time: "06:00", cycleTime: 1.08, speed: 59000, uptime: 96.0 },
      { time: "08:00", cycleTime: 1.04, speed: 62000, uptime: 98.1 },
      { time: "10:00", cycleTime: 1.03, speed: 63100, uptime: 98.5 },
      { time: "12:00", cycleTime: 1.15, speed: 56000, uptime: 91.0 },
      { time: "14:00", cycleTime: 1.05, speed: 61800, uptime: 97.4 },
      { time: "16:00", cycleTime: 1.02, speed: 64000, uptime: 98.9 },
      { time: "18:00", cycleTime: 1.04, speed: 62500, uptime: 97.8 },
      { time: "20:00", cycleTime: 1.06, speed: 61200, uptime: 96.9 },
      { time: "22:00", cycleTime: 1.05, speed: 62000, uptime: 97.5 },
    ],
    lines: [
      {
        id: "line-b1",
        factoryId: "berlin",
        name: "Line A — 330ml Euro Can",
        type: "Canning",
        status: "running",
        kpi: {
          factoryName: "Line A — 330ml Euro Can",
          actualSpeed: 75000,
          actualProduction: 180000,
          lastHourCycleTime: 0.92,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 91.2,
          sle: 96.1,
          usle: 94.0,
          productionVolume: 620000,
          productionQuality: 99.8,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(91.2, 210, 97.8),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-b2",
        factoryId: "berlin",
        name: "Line B — 500ml rPET",
        type: "rPET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line B — 500ml rPET",
          actualSpeed: 52000,
          actualProduction: 125000,
          lastHourCycleTime: 1.1,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 88.0,
          sle: 93.8,
          usle: 91.2,
          productionVolume: 430000,
          productionQuality: 99.7,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(88.0, 190, 95.8),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "tokyo",
    name: "Tokyo Bottling Facility",
    location: "Tokyo, Japan",
    kpi: {
      factoryName: "Tokyo Bottling Facility",
      actualSpeed: 48900,
      actualProduction: 372000,
      lastHourCycleTime: 1.18,
      activeLinesRatio: { active: 3, total: 4 },
      oee: 81.3,
      sle: 87.5,
      usle: 84.1,
      productionVolume: 1250000,
      productionQuality: 99.1,
    },
    lossTree: {
      onPercentage: 81.3,
      offPercentage: 18.7,
      qualityLossPercentage: 4.1,
      speedLossPercentage: 7.9,
      reasons: [
        { name: "Breakdown", percentage: 5.6, durationMinutes: 81 },
        { name: "Cleansing process", percentage: 4.2, durationMinutes: 60 },
        { name: "Change over time", percentage: 4.0, durationMinutes: 58 },
        { name: "Idle", percentage: 3.1, durationMinutes: 45 },
        { name: "Minor stops", percentage: 1.8, durationMinutes: 26 },
      ],
    },
    timeline: sampleTimeline,
    trendData: sampleHourlyTrend,
    lines: [
      {
        id: "line-t1",
        factoryId: "tokyo",
        name: "Line 1 — 300ml Mini PET",
        type: "PET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 300ml Mini PET",
          actualSpeed: 51000,
          actualProduction: 110000,
          lastHourCycleTime: 1.14,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 84.1,
          sle: 89.2,
          usle: 86.8,
          productionVolume: 390000,
          productionQuality: 99.3,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(84.1, 170, 94.2),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "london",
    name: "London Thames Plant",
    location: "London, United Kingdom",
    kpi: {
      factoryName: "London Thames Plant",
      actualSpeed: 45800,
      actualProduction: 348000,
      lastHourCycleTime: 1.22,
      activeLinesRatio: { active: 4, total: 5 },
      oee: 79.8,
      sle: 86.1,
      usle: 82.5,
      productionVolume: 1180000,
      productionQuality: 98.9,
    },
    lossTree: {
      onPercentage: 79.8,
      offPercentage: 20.2,
      qualityLossPercentage: 4.8,
      speedLossPercentage: 8.6,
      reasons: [
        { name: "Breakdown", percentage: 6.2, durationMinutes: 89 },
        { name: "Cleansing process", percentage: 4.8, durationMinutes: 69 },
        { name: "Change over time", percentage: 4.4, durationMinutes: 63 },
        { name: "Idle", percentage: 3.0, durationMinutes: 43 },
        { name: "Minor stops", percentage: 1.8, durationMinutes: 26 },
      ],
    },
    timeline: sampleTimeline,
    trendData: sampleHourlyTrend,
    lines: [
      {
        id: "line-l1",
        factoryId: "london",
        name: "Line 1 — 500ml Diet Coke PET",
        type: "PET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 500ml Diet Coke PET",
          actualSpeed: 47000,
          actualProduction: 98000,
          lastHourCycleTime: 1.2,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 80.5,
          sle: 86.8,
          usle: 83.2,
          productionVolume: 340000,
          productionQuality: 99.0,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(80.5, 155, 92.5),
        trendData: sampleHourlyTrend,
      },
    ],
  },
];

// Helper functions for accessing mock data
export function getAllFactories(): FactoryData[] {
  return factoriesData;
}

export function getFactoryById(id: string): FactoryData | undefined {
  return factoriesData.find((f) => f.id.toLowerCase() === id.toLowerCase());
}

export function getLineById(factoryId: string, lineId: string) {
  const factory = getFactoryById(factoryId);
  if (!factory) return undefined;
  return factory.lines.find((l) => l.id.toLowerCase() === lineId.toLowerCase());
}
