import {
  ActivityDataPoint,
  FactoryData,
  MachineData,
  TimelineSegment,
  TrendDataPoint,
} from "@/types/mes";
import { generateTabbedMetrics } from "./helpers/metrics";

// Shared 24-hour trend series for Cycle Time, Speed, and Uptime
export const sampleHourlyTrend: TrendDataPoint[] = [
  { time: "06:00", cycleTime: 1.15, speed: 52000, uptime: 94.2 },
  { time: "08:00", cycleTime: 1.12, speed: 54500, uptime: 96.5 },
  { time: "10:00", cycleTime: 1.28, speed: 48200, uptime: 88.0 },
  { time: "12:00", cycleTime: 1.14, speed: 53800, uptime: 95.1 },
  { time: "14:00", cycleTime: 1.1, speed: 55400, uptime: 97.4 },
  { time: "16:00", cycleTime: 1.22, speed: 50100, uptime: 91.3 },
  { time: "18:00", cycleTime: 1.11, speed: 55000, uptime: 96.8 },
  { time: "20:00", cycleTime: 1.13, speed: 54200, uptime: 95.5 },
  { time: "22:00", cycleTime: 1.18, speed: 51900, uptime: 93.7 },
];

export const sampleTimeline: TimelineSegment[] = [
  {
    id: "t1",
    startTime: "06:00",
    endTime: "08:30",
    status: "OFF",
    durationMinutes: 150,
    reason: "Conveyor Jam (Downtime)",
  },
  {
    id: "t2",
    startTime: "08:30",
    endTime: "13:00",
    status: "ON",
    durationMinutes: 270,
    reason: "Normal Production (Uptime)",
  },
  {
    id: "t3",
    startTime: "13:00",
    endTime: "15:30",
    status: "IDLE",
    durationMinutes: 150,
    reason: "Scheduled CIP Sanitization (Scheduled Downtime)",
  },
  {
    id: "t4",
    startTime: "15:30",
    endTime: "17:00",
    status: "OFF",
    durationMinutes: 90,
    reason: "Capper Head Sensor Fault (Downtime)",
  },
  {
    id: "t5",
    startTime: "17:00",
    endTime: "22:00",
    status: "ON",
    durationMinutes: 300,
    reason: "Normal Production (Uptime)",
  },
];

export const sampleActivityData: ActivityDataPoint[] = [
  { id: "a1", date: "24 Jan", time: "06:00", oee: 82.5, mtbf: 238, uptime: 93.0 },
  { id: "a2", date: "24 Jan", time: "07:00", oee: 85.0, mtbf: 256, uptime: 95.5 },
  { id: "a3", date: "24 Jan", time: "08:00", oee: 84.2, mtbf: 254, uptime: 94.8 },
  { id: "a4", date: "24 Jan", time: "09:00", oee: 80.5, mtbf: 229, uptime: 91.2 },
  { id: "a5", date: "24 Jan", time: "10:00", oee: 75.0, mtbf: 198, uptime: 86.4 },
  { id: "a6", date: "24 Jan", time: "11:00", oee: 71.5, mtbf: 170, uptime: 82.0 },
  { id: "a7", date: "24 Jan", time: "12:00", oee: 68.0, mtbf: 152, uptime: 78.5 },
  { id: "a8", date: "24 Jan", time: "13:00", oee: 73.5, mtbf: 177, uptime: 83.2 },
  { id: "a9", date: "24 Jan", time: "14:00", oee: 79.0, mtbf: 214, uptime: 88.6 },
  { id: "a10", date: "24 Jan", time: "15:00", oee: 84.8, mtbf: 243, uptime: 94.0 },
  { id: "a11", date: "24 Jan", time: "16:00", oee: 83.2, mtbf: 238, uptime: 92.8 },
  { id: "a12", date: "24 Jan", time: "17:00", oee: 78.5, mtbf: 217, uptime: 87.5 },
  { id: "a13", date: "24 Jan", time: "18:00", oee: 72.8, mtbf: 184, uptime: 81.0 },
  { id: "a14", date: "24 Jan", time: "19:00", oee: 67.5, mtbf: 155, uptime: 77.0 },
  { id: "a15", date: "24 Jan", time: "20:00", oee: 70.0, mtbf: 164, uptime: 80.5 },
  { id: "a16", date: "24 Jan", time: "21:00", oee: 81.5, mtbf: 224, uptime: 90.0 },
  { id: "a17", date: "24 Jan", time: "22:00", oee: 92.0, mtbf: 300, uptime: 98.2 },
];

export const factoriesData: FactoryData[] = [
  {
    id: "atlanta",
    name: "Atlanta Bottling Complex",
    location: "Atlanta, GA, USA",
    kpi: {
      factoryName: "Atlanta Bottling Complex",
      actualSpeed: 54200,
      actualProduction: 418500,
      lastHourCycleTime: 1.95,
      activeLinesRatio: { active: 5, total: 6 },
      oee: 84.6,
      sle: 91.4,
      usle: 88.2,
      productionVolume: 1420000,
      productionQuality: 99.4,
    },
    totalProduction: {
      bottles: 500000,
      packs: 50000,
      pallets: 10000,
    },
    performanceKpi: {
      performance: 76,
      quality: 94,
    },
    usageKpi: {
      energy: {
        perLiter: 420,
        perBottle: 210,
        unit: "J",
      },
      water: {
        perLiter: 380,
        perBottle: 190,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 84.6,
      offPercentage: 15.4,
      qualityLossPercentage: 3.2,
      speedLossPercentage: 6.8,
      reasons: [
        { name: "Breakdown", percentage: 4.8, durationMinutes: 69 },
        { name: "Cleansing process", percentage: 3.5, durationMinutes: 50 },
        { name: "Change over time", percentage: 3.2, durationMinutes: 46 },
        { name: "Idle", percentage: 2.4, durationMinutes: 35 },
        { name: "Minor stops", percentage: 1.5, durationMinutes: 22 },
      ],
    },
    timeline: sampleTimeline,
    timelineStats: {
      uptimePercentage: 59,
      downtimePercentage: 25,
      scheduledDowntimePercentage: 16,
      uptimeMinutes: 570,
      downtimeMinutes: 240,
      scheduledDowntimeMinutes: 150,
    },
    trendData: [
      { time: "06:00", cycleTime: 1.75, speed: 52000, uptime: 92.5 },
      { time: "08:00", cycleTime: 1.88, speed: 54500, uptime: 94.0 },
      { time: "10:00", cycleTime: 2.55, speed: 46200, uptime: 81.5 },
      { time: "12:00", cycleTime: 1.92, speed: 53800, uptime: 93.1 },
      { time: "14:00", cycleTime: 1.58, speed: 57400, uptime: 96.2 },
      { time: "16:00", cycleTime: 2.3, speed: 49100, uptime: 86.3 },
      { time: "18:00", cycleTime: 1.85, speed: 55000, uptime: 94.8 },
      { time: "20:00", cycleTime: 1.96, speed: 53200, uptime: 92.5 },
      { time: "22:00", cycleTime: 1.78, speed: 54900, uptime: 94.2 },
    ],
    lines: [
      {
        id: "line-1",
        factoryId: "atlanta",
        name: "Line 1 — 500ml PET",
        type: "PET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 500ml PET",
          actualSpeed: 58000,
          actualProduction: 82400,
          lastHourCycleTime: 1.08,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 88.2,
          sle: 93.5,
          usle: 90.1,
          productionVolume: 285000,
          productionQuality: 99.7,
        },
        lineProduction: {
          ratePerHour: 5000,
          rateUnit: "bph",
          actualProduction: 7000,
          actualUnit: "KM",
          yieldPercentage: 75,
        },
        linePerformance: {
          oee: 76,
          availability: 80,
          performance: 30,
          quality: 60,
        },
        powerKpi: {
          energyUsed: 5000,
          energyUnit: "KWH",
          powerFactor: 7000,
          secondaryEnergyUsed: 5000,
          secondaryEnergyUnit: "KWH",
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(88.2, 195, 96.4),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-2",
        factoryId: "atlanta",
        name: "Line 2 — 330ml Sleek Can",
        type: "Canning",
        status: "running",
        kpi: {
          factoryName: "Line 2 — 330ml Sleek Can",
          actualSpeed: 72000,
          actualProduction: 104500,
          lastHourCycleTime: 0.94,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 86.5,
          sle: 92.0,
          usle: 89.4,
          productionVolume: 360000,
          productionQuality: 99.2,
        },
        lineProduction: {
          ratePerHour: 6200,
          rateUnit: "bph",
          actualProduction: 8400,
          actualUnit: "KM",
          yieldPercentage: 88,
        },
        linePerformance: {
          oee: 84,
          availability: 89,
          performance: 78,
          quality: 92,
        },
        powerKpi: {
          energyUsed: 4800,
          energyUnit: "KWH",
          powerFactor: 7400,
          secondaryEnergyUsed: 4800,
          secondaryEnergyUnit: "KWH",
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(86.5, 180, 95.0),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-3",
        factoryId: "atlanta",
        name: "Line 3 — 2.0L Family PET",
        type: "PET Bottling",
        status: "downtime",
        kpi: {
          factoryName: "Line 3 — 2.0L Family PET",
          actualSpeed: 28000,
          actualProduction: 38200,
          lastHourCycleTime: 1.62,
          activeLinesRatio: { active: 0, total: 1 },
          oee: 72.1,
          sle: 81.3,
          usle: 76.8,
          productionVolume: 145000,
          productionQuality: 98.6,
        },
        lineProduction: {
          ratePerHour: 2800,
          rateUnit: "bph",
          actualProduction: 3500,
          actualUnit: "KM",
          yieldPercentage: 54,
        },
        linePerformance: {
          oee: 58,
          availability: 62,
          performance: 45,
          quality: 65,
        },
        powerKpi: {
          energyUsed: 3100,
          energyUnit: "KWH",
          powerFactor: 6100,
          secondaryEnergyUsed: 3100,
          secondaryEnergyUnit: "KWH",
        },
        timeline: [
          {
            id: "l3-1",
            startTime: "06:00",
            endTime: "11:00",
            status: "ON",
            durationMinutes: 300,
            reason: "Normal Production",
          },
          {
            id: "l3-2",
            startTime: "11:00",
            endTime: "14:30",
            status: "OFF",
            durationMinutes: 210,
            reason: "Blow Molder Seal Rupture",
          },
          {
            id: "l3-3",
            startTime: "14:30",
            endTime: "22:00",
            status: "IDLE",
            durationMinutes: 450,
            reason: "Maintenance Scheduled",
          },
        ],
        tabbedMetrics: generateTabbedMetrics(72.1, 110, 84.5),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-4",
        factoryId: "atlanta",
        name: "Line 4 — 355ml Heritage Glass",
        type: "Glass Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 4 — 355ml Heritage Glass",
          actualSpeed: 42000,
          actualProduction: 61800,
          lastHourCycleTime: 1.25,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 83.4,
          sle: 89.8,
          usle: 86.5,
          productionVolume: 215000,
          productionQuality: 99.5,
        },
        lineProduction: {
          ratePerHour: 4200,
          rateUnit: "bph",
          actualProduction: 6100,
          actualUnit: "KM",
          yieldPercentage: 79,
        },
        linePerformance: {
          oee: 82,
          availability: 86,
          performance: 72,
          quality: 88,
        },
        powerKpi: {
          energyUsed: 5100,
          energyUnit: "KWH",
          powerFactor: 6950,
          secondaryEnergyUsed: 5100,
          secondaryEnergyUnit: "KWH",
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(83.4, 165, 93.8),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "berlin",
    name: "Berlin Packaging Hub",
    location: "Berlin, Germany",
    kpi: {
      factoryName: "Berlin Packaging Hub",
      actualSpeed: 61500,
      actualProduction: 495000,
      lastHourCycleTime: 0.65,
      activeLinesRatio: { active: 4, total: 4 },
      oee: 89.1,
      sle: 94.6,
      usle: 92.3,
      productionVolume: 1680000,
      productionQuality: 99.8,
    },
    totalProduction: {
      bottles: 720000,
      packs: 72000,
      pallets: 14400,
    },
    performanceKpi: {
      performance: 88,
      quality: 98,
    },
    usageKpi: {
      energy: {
        perLiter: 360,
        perBottle: 180,
        unit: "J",
      },
      water: {
        perLiter: 310,
        perBottle: 155,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 89.1,
      offPercentage: 10.9,
      qualityLossPercentage: 1.8,
      speedLossPercentage: 4.2,
      reasons: [
        { name: "Breakdown", percentage: 3.1, durationMinutes: 45 },
        { name: "Cleansing process", percentage: 2.8, durationMinutes: 40 },
        { name: "Change over time", percentage: 2.4, durationMinutes: 35 },
        { name: "Idle", percentage: 1.6, durationMinutes: 23 },
        { name: "Minor stops", percentage: 1.0, durationMinutes: 14 },
      ],
    },
    timeline: [
      {
        id: "b1",
        startTime: "06:00",
        endTime: "11:30",
        status: "ON",
        durationMinutes: 330,
        reason: "Normal Canning (Uptime)",
      },
      {
        id: "b2",
        startTime: "11:30",
        endTime: "12:30",
        status: "IDLE",
        durationMinutes: 60,
        reason: "Scheduled Can Seamer Changeover (Scheduled Downtime)",
      },
      {
        id: "b3",
        startTime: "12:30",
        endTime: "17:30",
        status: "ON",
        durationMinutes: 300,
        reason: "Normal Canning (Uptime)",
      },
      {
        id: "b4",
        startTime: "17:30",
        endTime: "18:00",
        status: "OFF",
        durationMinutes: 30,
        reason: "Palletizer Sensor Fault (Downtime)",
      },
      {
        id: "b5",
        startTime: "18:00",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 240,
        reason: "Normal Canning (Uptime)",
      },
    ],
    timelineStats: {
      uptimePercentage: 91,
      downtimePercentage: 3,
      scheduledDowntimePercentage: 6,
      uptimeMinutes: 870,
      downtimeMinutes: 30,
      scheduledDowntimeMinutes: 60,
    },
    trendData: [
      { time: "06:00", cycleTime: 0.62, speed: 59000, uptime: 96.0 },
      { time: "08:00", cycleTime: 0.58, speed: 62000, uptime: 98.1 },
      { time: "10:00", cycleTime: 0.82, speed: 63100, uptime: 98.5 },
      { time: "12:00", cycleTime: 0.64, speed: 56000, uptime: 91.0 },
      { time: "14:00", cycleTime: 0.52, speed: 61800, uptime: 97.4 },
      { time: "16:00", cycleTime: 0.74, speed: 64000, uptime: 98.9 },
      { time: "18:00", cycleTime: 0.68, speed: 62500, uptime: 97.8 },
      { time: "20:00", cycleTime: 0.55, speed: 61200, uptime: 96.9 },
      { time: "22:00", cycleTime: 0.6, speed: 62000, uptime: 97.5 },
    ],
    lines: [
      {
        id: "line-b1",
        factoryId: "berlin",
        name: "Line A — 330ml Euro Can",
        type: "Canning",
        status: "running",
        kpi: {
          factoryName: "Line A — 330ml Euro Can",
          actualSpeed: 75000,
          actualProduction: 180000,
          lastHourCycleTime: 0.92,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 91.2,
          sle: 96.1,
          usle: 94.0,
          productionVolume: 620000,
          productionQuality: 99.8,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(91.2, 210, 97.8),
        trendData: sampleHourlyTrend,
      },
      {
        id: "line-b2",
        factoryId: "berlin",
        name: "Line B — 500ml rPET",
        type: "rPET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line B — 500ml rPET",
          actualSpeed: 52000,
          actualProduction: 125000,
          lastHourCycleTime: 1.1,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 88.0,
          sle: 93.8,
          usle: 91.2,
          productionVolume: 430000,
          productionQuality: 99.7,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(88.0, 190, 95.8),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "tokyo",
    name: "Tokyo Bottling Facility",
    location: "Tokyo, Japan",
    kpi: {
      factoryName: "Tokyo Bottling Facility",
      actualSpeed: 48900,
      actualProduction: 372000,
      lastHourCycleTime: 1.35,
      activeLinesRatio: { active: 3, total: 4 },
      oee: 81.3,
      sle: 87.5,
      usle: 84.1,
      productionVolume: 1250000,
      productionQuality: 99.1,
    },
    totalProduction: {
      bottles: 380000,
      packs: 38000,
      pallets: 7600,
    },
    performanceKpi: {
      performance: 65,
      quality: 92,
    },
    usageKpi: {
      energy: {
        perLiter: 490,
        perBottle: 245,
        unit: "J",
      },
      water: {
        perLiter: 460,
        perBottle: 230,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 81.3,
      offPercentage: 18.7,
      qualityLossPercentage: 4.1,
      speedLossPercentage: 7.9,
      reasons: [
        { name: "Breakdown", percentage: 5.6, durationMinutes: 81 },
        { name: "Cleansing process", percentage: 4.2, durationMinutes: 60 },
        { name: "Change over time", percentage: 4.0, durationMinutes: 58 },
        { name: "Idle", percentage: 3.1, durationMinutes: 45 },
        { name: "Minor stops", percentage: 1.8, durationMinutes: 26 },
      ],
    },
    timeline: [
      {
        id: "tokyo-t1",
        startTime: "06:00",
        endTime: "09:30",
        status: "ON",
        durationMinutes: 210,
        reason: "Normal Bottling Operation (Uptime)",
      },
      {
        id: "tokyo-t2",
        startTime: "09:30",
        endTime: "10:15",
        status: "OFF",
        durationMinutes: 45,
        reason: "Cap Feeder Alignment (Downtime)",
      },
      {
        id: "tokyo-t3",
        startTime: "10:15",
        endTime: "14:00",
        status: "ON",
        durationMinutes: 225,
        reason: "Normal Bottling Operation (Uptime)",
      },
      {
        id: "tokyo-t4",
        startTime: "14:00",
        endTime: "15:30",
        status: "IDLE",
        durationMinutes: 90,
        reason: "Scheduled Line Flushing (Scheduled Downtime)",
      },
      {
        id: "tokyo-t5",
        startTime: "15:30",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 390,
        reason: "Normal Bottling Operation (Uptime)",
      },
    ],
    timelineStats: {
      uptimePercentage: 86,
      downtimePercentage: 5,
      scheduledDowntimePercentage: 9,
      uptimeMinutes: 825,
      downtimeMinutes: 45,
      scheduledDowntimeMinutes: 90,
    },
    trendData: [
      { time: "06:00", cycleTime: 1.25, speed: 46000, uptime: 88.5 },
      { time: "08:00", cycleTime: 1.12, speed: 51200, uptime: 93.0 },
      { time: "10:00", cycleTime: 1.75, speed: 42100, uptime: 82.4 },
      { time: "12:00", cycleTime: 1.38, speed: 49800, uptime: 91.2 },
      { time: "14:00", cycleTime: 1.02, speed: 54000, uptime: 95.0 },
      { time: "16:00", cycleTime: 1.55, speed: 43500, uptime: 85.8 },
      { time: "18:00", cycleTime: 1.3, speed: 48200, uptime: 90.0 },
      { time: "20:00", cycleTime: 1.18, speed: 50500, uptime: 92.5 },
      { time: "22:00", cycleTime: 1.24, speed: 49100, uptime: 91.8 },
    ],
    lines: [
      {
        id: "line-t1",
        factoryId: "tokyo",
        name: "Line 1 — 300ml Mini PET",
        type: "PET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 300ml Mini PET",
          actualSpeed: 51000,
          actualProduction: 110000,
          lastHourCycleTime: 1.14,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 84.1,
          sle: 89.2,
          usle: 86.8,
          productionVolume: 390000,
          productionQuality: 99.3,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(84.1, 170, 94.2),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "london",
    name: "London Thames Plant",
    location: "London, United Kingdom",
    kpi: {
      factoryName: "London Thames Plant",
      actualSpeed: 45800,
      actualProduction: 348000,
      lastHourCycleTime: 2.45,
      activeLinesRatio: { active: 4, total: 5 },
      oee: 79.8,
      sle: 86.1,
      usle: 82.5,
      productionVolume: 1180000,
      productionQuality: 98.9,
    },
    totalProduction: {
      bottles: 440000,
      packs: 44000,
      pallets: 8800,
    },
    performanceKpi: {
      performance: 58,
      quality: 86,
    },
    usageKpi: {
      energy: {
        perLiter: 530,
        perBottle: 265,
        unit: "J",
      },
      water: {
        perLiter: 510,
        perBottle: 255,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 79.8,
      offPercentage: 20.2,
      qualityLossPercentage: 4.8,
      speedLossPercentage: 8.6,
      reasons: [
        { name: "Breakdown", percentage: 6.2, durationMinutes: 89 },
        { name: "Cleansing process", percentage: 4.8, durationMinutes: 69 },
        { name: "Change over time", percentage: 4.4, durationMinutes: 63 },
        { name: "Idle", percentage: 3.0, durationMinutes: 43 },
        { name: "Minor stops", percentage: 1.8, durationMinutes: 26 },
      ],
    },
    timeline: [
      {
        id: "london-t1",
        startTime: "06:00",
        endTime: "08:30",
        status: "OFF",
        durationMinutes: 150,
        reason: "Palletizer Conveyor Breakdown (Downtime)",
      },
      {
        id: "london-t2",
        startTime: "08:30",
        endTime: "12:30",
        status: "ON",
        durationMinutes: 240,
        reason: "Normal Bottling Operation (Uptime)",
      },
      {
        id: "london-t3",
        startTime: "12:30",
        endTime: "14:00",
        status: "IDLE",
        durationMinutes: 90,
        reason: "Scheduled Line Maintenance (Scheduled Downtime)",
      },
      {
        id: "london-t4",
        startTime: "14:00",
        endTime: "16:00",
        status: "OFF",
        durationMinutes: 120,
        reason: "Blow Molder Seal Jam (Downtime)",
      },
      {
        id: "london-t5",
        startTime: "16:00",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 360,
        reason: "Normal Bottling Operation (Uptime)",
      },
    ],
    timelineStats: {
      uptimePercentage: 63,
      downtimePercentage: 28,
      scheduledDowntimePercentage: 9,
      uptimeMinutes: 600,
      downtimeMinutes: 270,
      scheduledDowntimeMinutes: 90,
    },
    trendData: [
      { time: "06:00", cycleTime: 2.2, speed: 43200, uptime: 84.2 },
      { time: "08:00", cycleTime: 2.5, speed: 45800, uptime: 88.0 },
      { time: "10:00", cycleTime: 3.35, speed: 39500, uptime: 76.5 },
      { time: "12:00", cycleTime: 2.42, speed: 46200, uptime: 89.1 },
      { time: "14:00", cycleTime: 1.95, speed: 47900, uptime: 91.7 },
      { time: "16:00", cycleTime: 2.9, speed: 42100, uptime: 82.0 },
      { time: "18:00", cycleTime: 2.3, speed: 45800, uptime: 87.4 },
      { time: "20:00", cycleTime: 2.55, speed: 44500, uptime: 86.6 },
      { time: "22:00", cycleTime: 2.38, speed: 46000, uptime: 89.5 },
    ],
    lines: [
      {
        id: "line-l1",
        factoryId: "london",
        name: "Line 1 — 500ml Diet Coke PET",
        type: "PET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 500ml Diet Coke PET",
          actualSpeed: 47000,
          actualProduction: 98000,
          lastHourCycleTime: 1.2,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 80.5,
          sle: 86.8,
          usle: 83.2,
          productionVolume: 340000,
          productionQuality: 99.0,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(80.5, 155, 92.5),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "mexico-city",
    name: "Mexico City Plant",
    location: "Mexico City, Mexico",
    kpi: {
      factoryName: "Mexico City Plant",
      actualSpeed: 56400,
      actualProduction: 435000,
      lastHourCycleTime: 0.85,
      activeLinesRatio: { active: 5, total: 6 },
      oee: 86.2,
      sle: 92.8,
      usle: 89.6,
      productionVolume: 1540000,
      productionQuality: 99.6,
    },
    totalProduction: {
      bottles: 850000,
      packs: 85000,
      pallets: 17000,
    },
    performanceKpi: {
      performance: 84,
      quality: 96,
    },
    usageKpi: {
      energy: {
        perLiter: 390,
        perBottle: 195,
        unit: "J",
      },
      water: {
        perLiter: 340,
        perBottle: 170,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 86.2,
      offPercentage: 13.8,
      qualityLossPercentage: 2.5,
      speedLossPercentage: 5.4,
      reasons: [
        { name: "Breakdown", percentage: 3.8, durationMinutes: 55 },
        { name: "Cleansing process", percentage: 3.2, durationMinutes: 46 },
        { name: "Change over time", percentage: 3.0, durationMinutes: 43 },
        { name: "Idle", percentage: 2.2, durationMinutes: 32 },
        { name: "Minor stops", percentage: 1.6, durationMinutes: 23 },
      ],
    },
    timeline: [
      {
        id: "mc-t1",
        startTime: "06:00",
        endTime: "13:00",
        status: "ON",
        durationMinutes: 420,
        reason: "Normal Mega-Line Production (Uptime)",
      },
      {
        id: "mc-t2",
        startTime: "13:00",
        endTime: "13:45",
        status: "IDLE",
        durationMinutes: 45,
        reason: "Scheduled Quick Cleansing (Scheduled Downtime)",
      },
      {
        id: "mc-t3",
        startTime: "13:45",
        endTime: "18:30",
        status: "ON",
        durationMinutes: 285,
        reason: "Normal Mega-Line Production (Uptime)",
      },
      {
        id: "mc-t4",
        startTime: "18:30",
        endTime: "19:15",
        status: "OFF",
        durationMinutes: 45,
        reason: "Case Packer Minor Stop (Downtime)",
      },
      {
        id: "mc-t5",
        startTime: "19:15",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 165,
        reason: "Normal Mega-Line Production (Uptime)",
      },
    ],
    timelineStats: {
      uptimePercentage: 91,
      downtimePercentage: 5,
      scheduledDowntimePercentage: 4,
      uptimeMinutes: 870,
      downtimeMinutes: 45,
      scheduledDowntimeMinutes: 45,
    },
    trendData: [
      { time: "06:00", cycleTime: 0.82, speed: 53800, uptime: 91.2 },
      { time: "08:00", cycleTime: 0.75, speed: 57200, uptime: 95.8 },
      { time: "10:00", cycleTime: 1.1, speed: 52400, uptime: 89.4 },
      { time: "12:00", cycleTime: 0.86, speed: 58500, uptime: 96.9 },
      { time: "14:00", cycleTime: 0.68, speed: 60100, uptime: 97.5 },
      { time: "16:00", cycleTime: 0.98, speed: 55000, uptime: 93.2 },
      { time: "18:00", cycleTime: 0.78, speed: 58600, uptime: 96.5 },
      { time: "20:00", cycleTime: 0.84, speed: 56900, uptime: 95.1 },
      { time: "22:00", cycleTime: 0.8, speed: 57600, uptime: 96.0 },
    ],
    lines: [
      {
        id: "line-m1",
        factoryId: "mexico-city",
        name: "Line 1 — 600ml Bottle",
        type: "PET Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 600ml Bottle",
          actualSpeed: 60000,
          actualProduction: 115000,
          lastHourCycleTime: 1.05,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 87.5,
          sle: 93.0,
          usle: 90.2,
          productionVolume: 420000,
          productionQuality: 99.7,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(87.5, 185, 95.5),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "sao-paulo",
    name: "São Paulo Bottling Works",
    location: "São Paulo, Brazil",
    kpi: {
      factoryName: "São Paulo Bottling Works",
      actualSpeed: 51200,
      actualProduction: 388000,
      lastHourCycleTime: 1.55,
      activeLinesRatio: { active: 4, total: 5 },
      oee: 83.1,
      sle: 89.9,
      usle: 86.4,
      productionVolume: 1310000,
      productionQuality: 99.3,
    },
    totalProduction: {
      bottles: 610000,
      packs: 61000,
      pallets: 12200,
    },
    performanceKpi: {
      performance: 74,
      quality: 91,
    },
    usageKpi: {
      energy: {
        perLiter: 440,
        perBottle: 220,
        unit: "J",
      },
      water: {
        perLiter: 410,
        perBottle: 205,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 83.1,
      offPercentage: 16.9,
      qualityLossPercentage: 3.6,
      speedLossPercentage: 6.9,
      reasons: [
        { name: "Breakdown", percentage: 5.1, durationMinutes: 73 },
        { name: "Cleansing process", percentage: 3.9, durationMinutes: 56 },
        { name: "Change over time", percentage: 3.7, durationMinutes: 53 },
        { name: "Idle", percentage: 2.6, durationMinutes: 37 },
        { name: "Minor stops", percentage: 1.6, durationMinutes: 23 },
      ],
    },
    timeline: [
      {
        id: "sp-t1",
        startTime: "06:00",
        endTime: "10:00",
        status: "ON",
        durationMinutes: 240,
        reason: "Normal Canning Production (Uptime)",
      },
      {
        id: "sp-t2",
        startTime: "10:00",
        endTime: "11:15",
        status: "OFF",
        durationMinutes: 75,
        reason: "Crown Sorter Jam (Downtime)",
      },
      {
        id: "sp-t3",
        startTime: "11:15",
        endTime: "15:30",
        status: "ON",
        durationMinutes: 255,
        reason: "Normal Canning Production (Uptime)",
      },
      {
        id: "sp-t4",
        startTime: "15:30",
        endTime: "17:00",
        status: "IDLE",
        durationMinutes: 90,
        reason: "Scheduled CIP Sanitization (Scheduled Downtime)",
      },
      {
        id: "sp-t5",
        startTime: "17:00",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 300,
        reason: "Normal Canning Production (Uptime)",
      },
    ],
    timelineStats: {
      uptimePercentage: 83,
      downtimePercentage: 8,
      scheduledDowntimePercentage: 9,
      uptimeMinutes: 795,
      downtimeMinutes: 75,
      scheduledDowntimeMinutes: 90,
    },
    trendData: [
      { time: "06:00", cycleTime: 1.4, speed: 48900, uptime: 88.0 },
      { time: "08:00", cycleTime: 1.52, speed: 51800, uptime: 92.5 },
      { time: "10:00", cycleTime: 2.1, speed: 44500, uptime: 83.3 },
      { time: "12:00", cycleTime: 1.56, speed: 52400, uptime: 93.8 },
      { time: "14:00", cycleTime: 1.24, speed: 54100, uptime: 95.4 },
      { time: "16:00", cycleTime: 1.85, speed: 48000, uptime: 89.6 },
      { time: "18:00", cycleTime: 1.48, speed: 51200, uptime: 92.1 },
      { time: "20:00", cycleTime: 1.58, speed: 50200, uptime: 90.9 },
      { time: "22:00", cycleTime: 1.44, speed: 52100, uptime: 93.0 },
    ],
    lines: [
      {
        id: "line-sp1",
        factoryId: "sao-paulo",
        name: "Line 1 — 350ml Sleek Can",
        type: "Canning",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 350ml Sleek Can",
          actualSpeed: 68000,
          actualProduction: 130000,
          lastHourCycleTime: 0.98,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 85.0,
          sle: 91.2,
          usle: 88.0,
          productionVolume: 410000,
          productionQuality: 99.4,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(85.0, 175, 94.0),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "madrid",
    name: "Madrid Packaging Center",
    location: "Madrid, Spain",
    kpi: {
      factoryName: "Madrid Packaging Center",
      actualSpeed: 53800,
      actualProduction: 402000,
      lastHourCycleTime: 3.25,
      activeLinesRatio: { active: 3, total: 4 },
      oee: 85.4,
      sle: 91.8,
      usle: 88.9,
      productionVolume: 1390000,
      productionQuality: 99.5,
    },
    totalProduction: {
      bottles: 320000,
      packs: 32000,
      pallets: 6400,
    },
    performanceKpi: {
      performance: 80,
      quality: 97,
    },
    usageKpi: {
      energy: {
        perLiter: 380,
        perBottle: 190,
        unit: "J",
      },
      water: {
        perLiter: 320,
        perBottle: 160,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 85.4,
      offPercentage: 14.6,
      qualityLossPercentage: 2.8,
      speedLossPercentage: 5.9,
      reasons: [
        { name: "Breakdown", percentage: 4.2, durationMinutes: 60 },
        { name: "Cleansing process", percentage: 3.4, durationMinutes: 49 },
        { name: "Change over time", percentage: 3.1, durationMinutes: 45 },
        { name: "Idle", percentage: 2.3, durationMinutes: 33 },
        { name: "Minor stops", percentage: 1.6, durationMinutes: 23 },
      ],
    },
    timeline: [
      {
        id: "mad-t1",
        startTime: "06:00",
        endTime: "09:00",
        status: "ON",
        durationMinutes: 180,
        reason: "Normal Glass Bottling (Uptime)",
      },
      {
        id: "mad-t2",
        startTime: "09:00",
        endTime: "10:30",
        status: "OFF",
        durationMinutes: 90,
        reason: "Bottle Washer Stoppage (Downtime)",
      },
      {
        id: "mad-t3",
        startTime: "10:30",
        endTime: "14:30",
        status: "ON",
        durationMinutes: 240,
        reason: "Normal Glass Bottling (Uptime)",
      },
      {
        id: "mad-t4",
        startTime: "14:30",
        endTime: "16:00",
        status: "IDLE",
        durationMinutes: 90,
        reason: "Scheduled Sanitization Cycle (Scheduled Downtime)",
      },
      {
        id: "mad-t5",
        startTime: "16:00",
        endTime: "17:00",
        status: "OFF",
        durationMinutes: 60,
        reason: "Conveyor Lubrication Check (Downtime)",
      },
      {
        id: "mad-t6",
        startTime: "17:00",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 300,
        reason: "Normal Glass Bottling (Uptime)",
      },
    ],
    timelineStats: {
      uptimePercentage: 75,
      downtimePercentage: 16,
      scheduledDowntimePercentage: 9,
      uptimeMinutes: 720,
      downtimeMinutes: 150,
      scheduledDowntimeMinutes: 90,
    },
    trendData: [
      { time: "06:00", cycleTime: 2.8, speed: 43500, uptime: 88.0 },
      { time: "08:00", cycleTime: 3.2, speed: 45600, uptime: 91.2 },
      { time: "10:00", cycleTime: 4.4, speed: 38900, uptime: 79.5 },
      { time: "12:00", cycleTime: 3.25, speed: 46800, uptime: 92.8 },
      { time: "14:00", cycleTime: 2.5, speed: 48200, uptime: 94.4 },
      { time: "16:00", cycleTime: 3.95, speed: 41100, uptime: 83.3 },
      { time: "18:00", cycleTime: 3.05, speed: 46400, uptime: 91.0 },
      { time: "20:00", cycleTime: 3.4, speed: 44100, uptime: 88.7 },
      { time: "22:00", cycleTime: 3.15, speed: 45000, uptime: 89.9 },
    ],
    lines: [
      {
        id: "line-m1",
        factoryId: "madrid",
        name: "Line 1 — 250ml Glass",
        type: "Glass Bottling",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 250ml Glass",
          actualSpeed: 46000,
          actualProduction: 92000,
          lastHourCycleTime: 1.22,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 84.8,
          sle: 91.0,
          usle: 88.1,
          productionVolume: 310000,
          productionQuality: 99.6,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(84.8, 180, 94.8),
        trendData: sampleHourlyTrend,
      },
    ],
  },
  {
    id: "sydney",
    name: "Sydney Beverage Hub",
    location: "Sydney, Australia",
    kpi: {
      factoryName: "Sydney Beverage Hub",
      actualSpeed: 49800,
      actualProduction: 365000,
      lastHourCycleTime: 1.05,
      activeLinesRatio: { active: 4, total: 5 },
      oee: 82.6,
      sle: 88.7,
      usle: 85.3,
      productionVolume: 1220000,
      productionQuality: 99.2,
    },
    totalProduction: {
      bottles: 540000,
      packs: 54000,
      pallets: 10800,
    },
    performanceKpi: {
      performance: 79,
      quality: 93,
    },
    usageKpi: {
      energy: {
        perLiter: 410,
        perBottle: 205,
        unit: "J",
      },
      water: {
        perLiter: 360,
        perBottle: 180,
        unit: "L",
      },
    },
    lossTree: {
      onPercentage: 82.6,
      offPercentage: 17.4,
      qualityLossPercentage: 3.9,
      speedLossPercentage: 7.2,
      reasons: [
        { name: "Breakdown", percentage: 5.3, durationMinutes: 76 },
        { name: "Cleansing process", percentage: 4.1, durationMinutes: 59 },
        { name: "Change over time", percentage: 3.8, durationMinutes: 55 },
        { name: "Idle", percentage: 2.7, durationMinutes: 39 },
        { name: "Minor stops", percentage: 1.5, durationMinutes: 22 },
      ],
    },
    timeline: [
      {
        id: "syd-t1",
        startTime: "06:00",
        endTime: "11:00",
        status: "ON",
        durationMinutes: 300,
        reason: "Normal Canning Operation (Uptime)",
      },
      {
        id: "syd-t2",
        startTime: "11:00",
        endTime: "12:15",
        status: "IDLE",
        durationMinutes: 75,
        reason: "Scheduled Seamer Adjustment (Scheduled Downtime)",
      },
      {
        id: "syd-t3",
        startTime: "12:15",
        endTime: "17:00",
        status: "ON",
        durationMinutes: 285,
        reason: "Normal Canning Operation (Uptime)",
      },
      {
        id: "syd-t4",
        startTime: "17:00",
        endTime: "17:45",
        status: "OFF",
        durationMinutes: 45,
        reason: "Batch Coder Sensor Jam (Downtime)",
      },
      {
        id: "syd-t5",
        startTime: "17:45",
        endTime: "22:00",
        status: "ON",
        durationMinutes: 255,
        reason: "Normal Canning Operation (Uptime)",
      },
    ],
    timelineStats: {
      uptimePercentage: 88,
      downtimePercentage: 5,
      scheduledDowntimePercentage: 7,
      uptimeMinutes: 840,
      downtimeMinutes: 45,
      scheduledDowntimeMinutes: 75,
    },
    trendData: [
      { time: "06:00", cycleTime: 0.98, speed: 47200, uptime: 87.5 },
      { time: "08:00", cycleTime: 0.9, speed: 50400, uptime: 91.8 },
      { time: "10:00", cycleTime: 1.35, speed: 44200, uptime: 82.0 },
      { time: "12:00", cycleTime: 1.05, speed: 51200, uptime: 93.1 },
      { time: "14:00", cycleTime: 0.85, speed: 53100, uptime: 94.6 },
      { time: "16:00", cycleTime: 1.2, speed: 48900, uptime: 88.0 },
      { time: "18:00", cycleTime: 0.98, speed: 51000, uptime: 92.8 },
      { time: "20:00", cycleTime: 1.06, speed: 49900, uptime: 91.2 },
      { time: "22:00", cycleTime: 0.94, speed: 52000, uptime: 93.5 },
    ],
    lines: [
      {
        id: "line-s1",
        factoryId: "sydney",
        name: "Line 1 — 375ml Can",
        type: "Canning",
        status: "running",
        kpi: {
          factoryName: "Line 1 — 375ml Can",
          actualSpeed: 64000,
          actualProduction: 122000,
          lastHourCycleTime: 1.01,
          activeLinesRatio: { active: 1, total: 1 },
          oee: 83.9,
          sle: 89.5,
          usle: 86.0,
          productionVolume: 380000,
          productionQuality: 99.2,
        },
        timeline: sampleTimeline,
        tabbedMetrics: generateTabbedMetrics(83.9, 168, 93.4),
        trendData: sampleHourlyTrend,
      },
    ],
  },
];

export function generateMachinesForLine(line: {
  id: string;
  name: string;
  type: string;
  status: "running" | "downtime" | "idle";
  kpi?: { actualSpeed?: number; lastHourCycleTime?: number };
}): MachineData[] {
  const isCanning = line.type.toLowerCase().includes("can");
  const isGlass = line.type.toLowerCase().includes("glass");
  const speedUnit = isCanning ? "cph" : "BPM";
  const baseSpeed = line.kpi?.actualSpeed ? Math.round(line.kpi.actualSpeed / 1) : 54000;
  const baseCycle = line.kpi?.lastHourCycleTime || 1.08;
  const isDowntime = line.status === "downtime";

  if (isCanning) {
    return [
      {
        id: `${line.id}-m1`,
        name: "Can Depalletizer & Infeed",
        subtitle: "Infeed & Ionized Air Rinse",
        status: isDowntime ? "idle" : "running",
        vitals: {
          speed: { value: Math.round(baseSpeed * 0.98), unit: speedUnit },
          cycleTime: { value: +(baseCycle * 0.96).toFixed(2), unit: "sec" },
          operatingTemp: { value: 21.5, unit: "°C" },
          pressure: { value: 5.5, unit: "bar" },
          telemetryStatus: isDowntime ? "Standby: Infeed paused" : "Live stream nominal (100ms)",
        },
        maintenance: {
          motorVibration: { value: 1.15, unit: "mm/s" },
          oilFluidLevel: { value: 94, unit: "%" },
          lastServiceDate: "12 Sep 2026",
          healthScore: { value: 97, unit: "%" },
          nextScheduledMaintenance: "In 72h (Shift A)",
        },
      },
      {
        id: `${line.id}-m2`,
        name: "Rotary Can Filler & Seamer",
        subtitle: "Isobaric Filling & Chuck Seaming",
        status: isDowntime ? "downtime" : "running",
        vitals: {
          speed: { value: isDowntime ? 0 : baseSpeed, unit: speedUnit },
          cycleTime: { value: +(baseCycle * 1.02).toFixed(2), unit: "sec" },
          operatingTemp: { value: 3.8, unit: "°C" },
          pressure: { value: isDowntime ? 1.2 : 4.8, unit: "bar" },
          telemetryStatus: isDowntime ? "Fault: Seamer chuck sensor alert" : "Isobaric counter-pressure locked",
        },
        maintenance: {
          motorVibration: { value: isDowntime ? 3.42 : 1.75, unit: "mm/s" },
          oilFluidLevel: { value: 85, unit: "%" },
          lastServiceDate: "25 Sep 2026",
          healthScore: { value: isDowntime ? 72 : 92, unit: "%" },
          nextScheduledMaintenance: isDowntime ? "Immediate attention required" : "In 36h (Shift C)",
        },
      },
      {
        id: `${line.id}-m3`,
        name: "Can Warmer & Coding Station",
        subtitle: "Condensation Heat & Date Coding",
        status: isDowntime ? "idle" : "running",
        vitals: {
          speed: { value: Math.round(baseSpeed * 0.99), unit: speedUnit },
          cycleTime: { value: +baseCycle.toFixed(2), unit: "sec" },
          operatingTemp: { value: 33.2, unit: "°C" },
          pressure: { value: 2.8, unit: "bar" },
          telemetryStatus: "Vision inspection 100% pass",
        },
        maintenance: {
          motorVibration: { value: 0.92, unit: "mm/s" },
          oilFluidLevel: { value: 96, unit: "%" },
          lastServiceDate: "05 Sep 2026",
          healthScore: { value: 98, unit: "%" },
          nextScheduledMaintenance: "In 120h (Shift B)",
        },
      },
      {
        id: `${line.id}-m4`,
        name: "Shrink Packer & Palletizer",
        subtitle: "Secondary Wrap & Robotic Stack",
        status: isDowntime ? "idle" : "running",
        vitals: {
          speed: { value: Math.round(baseSpeed * 0.95), unit: speedUnit },
          cycleTime: { value: +(baseCycle * 1.06).toFixed(2), unit: "sec" },
          operatingTemp: { value: 26.5, unit: "°C" },
          pressure: { value: 6.0, unit: "bar" },
          telemetryStatus: "Pallet hoist synchronized",
        },
        maintenance: {
          motorVibration: { value: 1.88, unit: "mm/s" },
          oilFluidLevel: { value: 82, unit: "%" },
          lastServiceDate: "19 Sep 2026",
          healthScore: { value: 89, unit: "%" },
          nextScheduledMaintenance: "In 24h (Shift B)",
        },
      },
    ];
  }

  if (isGlass) {
    return [
      {
        id: `${line.id}-m1`,
        name: "De-crater & Bottle Washer",
        subtitle: "Caustic Bath & Jet Rinse",
        status: isDowntime ? "idle" : "running",
        vitals: {
          speed: { value: Math.round(baseSpeed * 0.97), unit: "BPM" },
          cycleTime: { value: +(baseCycle * 1.04).toFixed(2), unit: "sec" },
          operatingTemp: { value: 74.5, unit: "°C" },
          pressure: { value: 4.5, unit: "bar" },
          telemetryStatus: "Caustic solution temp nominal",
        },
        maintenance: {
          motorVibration: { value: 1.62, unit: "mm/s" },
          oilFluidLevel: { value: 88, unit: "%" },
          lastServiceDate: "15 Sep 2026",
          healthScore: { value: 93, unit: "%" },
          nextScheduledMaintenance: "In 48h (Shift B)",
        },
      },
      {
        id: `${line.id}-m2`,
        name: "Crown Cork Rinser & Filler",
        subtitle: "Isobaric Filling & Crown Capping",
        status: isDowntime ? "downtime" : "running",
        vitals: {
          speed: { value: isDowntime ? 0 : baseSpeed, unit: "BPM" },
          cycleTime: { value: +(baseCycle * 1.05).toFixed(2), unit: "sec" },
          operatingTemp: { value: 4.5, unit: "°C" },
          pressure: { value: isDowntime ? 1.0 : 4.2, unit: "bar" },
          telemetryStatus: isDowntime ? "Stop: Crown feeder jam" : "Crown crimp torque verified",
        },
        maintenance: {
          motorVibration: { value: isDowntime ? 3.1 : 1.45, unit: "mm/s" },
          oilFluidLevel: { value: 89, unit: "%" },
          lastServiceDate: "29 Sep 2026",
          healthScore: { value: isDowntime ? 75 : 94, unit: "%" },
          nextScheduledMaintenance: isDowntime ? "Inspection in progress" : "In 60h (Shift A)",
        },
      },
      {
        id: `${line.id}-m3`,
        name: "Cold-Glue Body & Neck Labeler",
        subtitle: "Dual-Station Precision Application",
        status: isDowntime ? "idle" : "running",
        vitals: {
          speed: { value: Math.round(baseSpeed * 0.98), unit: "BPM" },
          cycleTime: { value: +(baseCycle * 1.02).toFixed(2), unit: "sec" },
          operatingTemp: { value: 23.8, unit: "°C" },
          pressure: { value: 3.5, unit: "bar" },
          telemetryStatus: "Glue viscosity nominal (450 mPa·s)",
        },
        maintenance: {
          motorVibration: { value: 1.18, unit: "mm/s" },
          oilFluidLevel: { value: 92, unit: "%" },
          lastServiceDate: "18 Sep 2026",
          healthScore: { value: 96, unit: "%" },
          nextScheduledMaintenance: "In 84h (Shift C)",
        },
      },
      {
        id: `${line.id}-m4`,
        name: "Crate Packer & Palletizer",
        subtitle: "Layer Gripper & Pallet Wrapping",
        status: isDowntime ? "idle" : "running",
        vitals: {
          speed: { value: Math.round(baseSpeed * 0.96), unit: "BPM" },
          cycleTime: { value: +(baseCycle * 1.08).toFixed(2), unit: "sec" },
          operatingTemp: { value: 22.8, unit: "°C" },
          pressure: { value: 6.4, unit: "bar" },
          telemetryStatus: "Layer gripper pneumatics active",
        },
        maintenance: {
          motorVibration: { value: 2.25, unit: "mm/s" },
          oilFluidLevel: { value: 80, unit: "%" },
          lastServiceDate: "10 Sep 2026",
          healthScore: { value: 87, unit: "%" },
          nextScheduledMaintenance: "In 18h (Shift A)",
        },
      },
    ];
  }

  // Standard PET Bottling (Default)
  return [
    {
      id: `${line.id}-m1`,
      name: "Depalletizer & Infeed Table",
      subtitle: "Automatic Sweep & Air Conveyor",
      status: isDowntime ? "idle" : "running",
      vitals: {
        speed: { value: Math.round(baseSpeed * 0.99), unit: "BPM" },
        cycleTime: { value: +(baseCycle * 0.98).toFixed(2), unit: "sec" },
        operatingTemp: { value: 20.8, unit: "°C" },
        pressure: { value: 5.6, unit: "bar" },
        telemetryStatus: "Infeed optical buffer 85%",
      },
      maintenance: {
        motorVibration: { value: 1.12, unit: "mm/s" },
        oilFluidLevel: { value: 94, unit: "%" },
        lastServiceDate: "14 Sep 2026",
        healthScore: { value: 98, unit: "%" },
        nextScheduledMaintenance: "In 72h (Shift A)",
      },
    },
    {
      id: `${line.id}-m2`,
      name: "Rotary Rinser & Filler",
      subtitle: "Tri-Block Rinser, Filler & Capper",
      status: isDowntime ? "downtime" : "running",
      vitals: {
        speed: { value: isDowntime ? 0 : baseSpeed, unit: "BPM" },
        cycleTime: { value: +baseCycle.toFixed(2), unit: "sec" },
        operatingTemp: { value: 4.2, unit: "°C" },
        pressure: { value: isDowntime ? 1.1 : 4.6, unit: "bar" },
        telemetryStatus: isDowntime ? "Warning: Filling valve offline" : "Filling valves synchronized (120/120)",
      },
      maintenance: {
        motorVibration: { value: isDowntime ? 3.85 : 1.48, unit: "mm/s" },
        oilFluidLevel: { value: 88, unit: "%" },
        lastServiceDate: "02 Oct 2026",
        healthScore: { value: isDowntime ? 70 : 94, unit: "%" },
        nextScheduledMaintenance: isDowntime ? "Technician dispatched" : "In 48h (Shift C)",
      },
    },
    {
      id: `${line.id}-m3`,
      name: "High-Speed Sleeve Labeler",
      subtitle: "Rotary Sleeve Applicator & Tunnel",
      status: isDowntime ? "idle" : "running",
      vitals: {
        speed: { value: Math.round(baseSpeed * 0.98), unit: "BPM" },
        cycleTime: { value: +(baseCycle * 1.01).toFixed(2), unit: "sec" },
        operatingTemp: { value: 68.4, unit: "°C" },
        pressure: { value: 3.2, unit: "bar" },
        telemetryStatus: "Steam heat tunnel stable (68°C)",
      },
      maintenance: {
        motorVibration: { value: 0.95, unit: "mm/s" },
        oilFluidLevel: { value: 91, unit: "%" },
        lastServiceDate: "20 Aug 2026",
        healthScore: { value: 96, unit: "%" },
        nextScheduledMaintenance: "In 96h (Shift B)",
      },
    },
    {
      id: `${line.id}-m4`,
      name: "Case Packer & Palletizer",
      subtitle: "Continuous Packer & Stretch Wrapper",
      status: isDowntime ? "idle" : "running",
      vitals: {
        speed: { value: Math.round(baseSpeed * 0.96), unit: "BPM" },
        cycleTime: { value: +(baseCycle * 1.05).toFixed(2), unit: "sec" },
        operatingTemp: { value: 24.2, unit: "°C" },
        pressure: { value: 6.2, unit: "bar" },
        telemetryStatus: "Servo axis 1-4 position nominal",
      },
      maintenance: {
        motorVibration: { value: 2.15, unit: "mm/s" },
        oilFluidLevel: { value: 82, unit: "%" },
        lastServiceDate: "28 Sep 2026",
        healthScore: { value: 89, unit: "%" },
        nextScheduledMaintenance: "In 24h (Shift B)",
      },
    },
  ];
}

// Populate mock machines for every line in all factories
for (const factory of factoriesData) {
  for (const line of factory.lines) {
    line.machines = generateMachinesForLine(line);
  }
}

export {
  getAllFactories,
  getFactoryById,
  getLineById,
} from "./helpers/factory";
